sudo: true
language: node_js
branches:
  only:
  - master
  - dev
node_js:
- '8'
cache: yarn
install:
- npm install
- npm install -g @angular/cli
services:
- xvfb
before_install:
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
before_deploy:
- ng build --prod
deploy:
- provider: firebase
  skip_cleanup: true
  token:
    secure: Yh02Z602qrSeI/bJkgx/f23fAXIrNEJ3vRiA1zwMi9cwS1M6ePmH6jROXORg5yDA/yBIxlUiNTXN4KViJnCsbRqTKSle6Z7DcLXlFL+rPzi2LndTX6ktzPo9AIjsCJ6Tn2uxlg74Uvm4qj1rBW5lydpE7Eg2XSNFS0qO38RpUqLfUY5t+JtfAr9erz8DWTI1PlON5OoNrXWmOGJsk8ks6P8yHE0L1jfy76H/lOp6Zq1G77qpMgeXcwz0tJSMb966YG1Ecp1+/YcB1MzB1MU5Hkzj5UBOU3RKvFTiZz0XltfdW1Ahlti/bfI7kz18NMg5o2deFlVwwa272IIej7cpO9tnwQ/rayFt+ys5TvHUAy8odM7scvyiYrbBjX6owID4icQxPfBSocsWFHIkPVHA9wR65otPmhwI6y1tDliy4989IiAl+6pQk6zoyLIPgh7MMhNHo7Ra+1FF0ml4MO2/JJTSYD8gnBlXt48oDMVw6I0Z/2eaURHK4BcZ4WiGNHPvc1lLBJjPtz1QtLp3j/Y7TxVnUImYmhWbIJAfDSFYSdHs+IEEebCk5V4KJnFlbGLjk4WYPkGBRQvPB4WW2nd78ZHiONXO6/oDUfDRrrhyH9fojS9RCaLuLXRoYPidG3ZBmAZ7B4DaNQkSYRh2c7ccNjgrnyUy5ijyKYbOYVNzNtg=
  project: hackpsu18
  on:
    repo: Hack-PSU/admin
    branch: master
