sudo: true
language: node_js
branches:
  only:
  - master
node_js:
- '8'
cache: yarn
install:
- npm install
- npm install -g @angular/cli

before_install:
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_deploy:
- ng build --prod
deploy:
- provider: firebase
  skip_cleanup: true
  token:
    secure: UppjTzfRFpwh09HFh1t0+WHFRw3ZQlRYZx5x0CdN4GAAyftnAgJ89AEl/aPtT37iCh/XtpamqBFdRxEDpwiCBuZ3p6FlvlnDMeoLaJuv/+rWjhA4nKxpNalI4doL2tlu2jLujPB1gN8mRjZtGqexQtDbnJIOYUaxX9soovrXbNqj1SBiCdREMQSYx7DxmdlRoYX+qfBNRLk+GEb3dNsvCsr2zXah4KBN2KIRZM/VfaNvyBJDUTVebXH2zqyVLU7bX6FyXvs/x9qAek+ExuWazL+3t3jjXa14QtmyajaTIMYaOcYQFdIaE2GJGBkJIUpNpTEtDyZzgbfEkGcQ1m3Lqvtnx4fBaWpVEz/2SHfgCiDPFlBvEK6GLf/yXeq/60RvzCY4B5GJtf+09MmiT1eKtBupPhghwb+gKZGDdedHUrzIgsY+v+I8yloRJb5VMAtcB4soCZafd6cNqoHdDHNKlgfCORE4/42QWeIAbpMU8PjIv76HQy/xvEP4lSJf+BvPzQfisad0F9WoYOr2Ww/bBIE5qHeg8xXR6PUX9u99cTEtm9vfYC7cNmHmRUYWfO8w++npxXjofb7+unFd0LuK1THCBRESTG4IfKiQ/qZxdEhAURe6pGCjiM0RZIAvJiYSb1URHvAKK5kszz1MmPPu9VXpbwCF3iJ8DGfv8+KuTLY=
  project: hackpsu18
  on:
    repo: Hack-PSU/admin
    branch: master
